# Generated by Django 3.2.8 on 2021-12-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2e', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_id',
        ),
        migrations.RemoveField(
            model_name='recipestosave',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='review_id',
        ),
    ]
