# Generated by Django 3.2.8 on 2021-12-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2e', '0002_auto_20211203_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestosave',
            name='recipe',
            field=models.IntegerField(default=0),
        ),
    ]
