# Generated by Django 3.2.8 on 2021-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2e', '0004_auto_20211215_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='recipe',
            field=models.CharField(max_length=50),
        ),
    ]
